name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql

    strategy:
      matrix:
        php: [5.6, 7.0, 7.1, 7.2, 7.3]

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, php-xml, ext-dom, phalcon3, pdo
        coverage: none

    - name: Install Phalcon Demo
      run: |
        git clone -b v1.0.2 https://github.com/Codeception/phalcon-demo.git framework-tests
        git --git-dir framework-tests/.git log -n 1
        composer update -d framework-tests --no-dev --prefer-dist --no-interaction

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run: |
        mysql -e "CREATE DATABASE phalcon_demo CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;"
        cat framework-tests/schemas/phalcon_demo.sql | mysql phalcon_demo
        php ./vendor/bin/codecept build -c framework-tests
        php ./vendor/bin/codecept run functional -c framework-tests
